# Generated by Django 4.2.20 on 2025-05-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0005_alter_nhapkho_ngay_tao_alter_nhapkho_thoi_gian_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khachhang', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã khách hàng')),
                ('ten_khachhang', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('nguoi_dai_dien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện')),
                ('sdt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['ten_khachhang'],
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('ma_ncc', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã nhà cung cấp')),
                ('ten_ncc', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('nguoi_dai_dien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện')),
                ('sdt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['ten_ncc'],
            },
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='gia_niem_yet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Giá niêm yết'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='gioi_han_duoi',
            field=models.PositiveIntegerField(default=0, verbose_name='Giới hạn dưới tồn kho'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã QR'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='quy_cach',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quy cách đóng gói'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='tinh_trang',
            field=models.CharField(choices=[('CON_HANG', 'Còn hàng'), ('GAN_HET_HANG', 'Gần hết hàng'), ('HET_HANG', 'Hết hàng')], default='CON_HANG', max_length=50, verbose_name='Tình trạng tồn kho'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='diachi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ liên hệ'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='sdt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='diachi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ người nhận'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='sdt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại người nhận'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='nguon_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuoiky.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='nguon_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuoiky.khachhang', verbose_name='Khách hàng'),
        ),
    ]
