# Generated by Django 4.2.20 on 2025-05-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0006_khachhang_nhacungcap_hanghoa_gia_niem_yet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('ma_kho', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã kho')),
                ('ten_kho', models.CharField(max_length=255, verbose_name='Tên kho')),
                ('loai_kho', models.CharField(choices=[('LUU_TRU', 'Kho lưu trữ'), ('DU_TRU', 'Kho dự trữ'), ('TRA_LAI', 'Kho trả lại')], max_length=50, verbose_name='Loại kho')),
                ('gioi_han', models.PositiveIntegerField(default=10000, verbose_name='Giới hạn số lượng')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
                'ordering': ['ten_kho'],
            },
        ),
        migrations.AddField(
            model_name='nhapkho',
            name='kho',
            field=models.ForeignKey(default='KHO_DEFAULT', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_nhap', to='cuoiky.kho', verbose_name='Kho nhập'),
        ),
        migrations.AddField(
            model_name='xuatkho',
            name='kho',
            field=models.ForeignKey(default='KHO_DEFAULT', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_xuat', to='cuoiky.kho', verbose_name='Kho xuất'),
        ),
        migrations.CreateModel(
            name='TonKhoTheoKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_kho_theo_kho', to='cuoiky.hanghoa', verbose_name='Hàng hóa')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_kho', to='cuoiky.kho', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn kho theo kho',
                'verbose_name_plural': 'Tồn kho theo kho',
                'unique_together': {('hang_hoa', 'kho')},
            },
        ),
    ]
