# Generated by Django 4.2.20 on 2025-05-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0007_kho_nhapkho_kho_xuatkho_kho_tonkhotheokho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanghoa',
            name='gia_niem_yet',
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='gioi_han_duoi',
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='quy_cach',
        ),
    ]
