# Generated by Django 4.2.20 on 2025-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0009_hanghoa_gioi_han_duoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='don_vi_tinh',
            field=models.CharField(choices=[('kg', 'kg'), ('tan', 'tấn'), ('bao', 'bao (50kg/bao)'), ('m3', 'm³'), ('lit', 'lít'), ('thung', 'thùng (18 lít/thùng)')], default='cái', max_length=50, verbose_name='Đơn vị tính'),
        ),
    ]
