# Generated by Django 4.2.20 on 2025-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0011_alter_hanghoa_don_vi_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhapkho',
            name='ly_do_khac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do nhập khác (nếu chọn Khác)'),
        ),
        migrations.AddField(
            model_name='xuatkho',
            name='ly_do_khac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xuất khác (nếu chọn Khác)'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='ly_do',
            field=models.CharField(choices=[('NHAP_BAN_THUONG', 'Nhập bán thường'), ('HOAN_HANG_TU_KH', 'Hoàn hàng từ khách'), ('KHAC', 'Khác')], default='NHAP_BAN_THUONG', max_length=50, verbose_name='Lý do nhập'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='ly_do',
            field=models.CharField(choices=[('XUAT_BAN_THUONG', 'Xuất bán thường'), ('KHAC', 'Khác')], default='XUAT_BAN_THUONG', max_length=50, verbose_name='Lý do xuất'),
        ),
    ]
