# Generated by Django 4.2.20 on 2025-05-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuoiky', '0012_nhapkho_ly_do_khac_xuatkho_ly_do_khac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='kiemke',
            name='muc_dich',
            field=models.CharField(blank=True, choices=[('DINH_KY', 'Kiểm kê định kỳ'), ('DOT_XUAT', 'Kiểm kê đột xuất'), ('DAU_KY', 'Kiểm kê đầu kỳ'), ('CUOI_KY', 'Kiểm kê cuối kỳ'), ('BAO_TRI', 'Kiểm kê bảo trì, bảo dưỡng')], max_length=20, null=True, verbose_name='Mục đích'),
        ),
    ]
