# Generated by Django 4.2.20 on 2025-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0013_remove_customuser_position_customuser_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='nhom_hang',
            field=models.CharField(choices=[('VAT_LIEU_THO', 'Vật liệu thô'), ('VAT_LIEU_HOAN_THIEN', 'Vật liệu hoàn thiện'), ('KIM_LOAI', 'Kim loại - sắt thép - inox'), ('DIEN_NUOC', 'Vật tư điện - nước')], default='VAT_LIEU_THO', max_length=50, verbose_name='Nhóm hàng'),
        ),
    ]
