# Generated by Django 4.2.20 on 2025-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0014_alter_hanghoa_nhom_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanghoa',
            name='don_gia_ban',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá bán'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='don_gia_nhap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá nhập'),
        ),
    ]
