# Generated by Django 4.2.20 on 2025-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0015_hanghoa_don_gia_ban_hanghoa_don_gia_nhap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhapkho',
            name='tinh_trang',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=50, verbose_name='Tình trạng phiếu'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='tinh_trang',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=50, verbose_name='Tình trạng phiếu'),
        ),
    ]
