# Generated by Django 4.2.20 on 2025-05-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0016_alter_nhapkho_tinh_trang_alter_xuatkho_tinh_trang'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietkiemke',
            name='kho',
            field=models.ForeignKey(default='KHO0001', on_delete=django.db.models.deletion.CASCADE, to='cuoiky.kho', verbose_name='Kho kiểm kê'),
            preserve_default=False,
        ),
    ]
