# Generated by Django 4.2.20 on 2025-05-23 12:57

import cuoiky.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0017_chitietkiemke_kho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhapkho',
            name='kho',
            field=models.ForeignKey(default=cuoiky.models.get_default_kho, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_nhap', to='cuoiky.kho', verbose_name='Kho nhập'),
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='kho',
            field=models.ForeignKey(default=cuoiky.models.get_default_kho, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_xuat', to='cuoiky.kho', verbose_name='Kho xuất'),
        ),
    ]
