# Generated by Django 4.2.20 on 2025-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0018_alter_nhapkho_kho_alter_xuatkho_kho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhapkho',
            name='ten_ncc_khac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
